[package]
name = "axelar-soroban-std-derive"
version = "0.1.0"
edition = { workspace = true }
description = "Proc macros for Axelar Soroban contracts"
license = "MIT"
publish = true

[lib]
proc-macro = true

[dependencies]
axelar-soroban-std = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
soroban-sdk = { workspace = true }
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[lints]
workspace = true
